### PR TITLE
Qc updates

### PR DESCRIPTION
**Pull request by DeniseSl22**
Added Recon as a database, and added "Guide to Pharmacology (Iuphar ligand) for RDF creation (was previously missing I believe).

### CODE REVIEW

**Comment by DeniseSl22** [comment]
I compiled the code locally (Wind. 7, with Ant), which was successful. Please check the additions I made (especially to the RDF related files, I'm not sure if the info I submitted now is complete, couldn't find documentation on what should go where and why @egonw .

**Comment by egonw** [comment]
The patch looks fine. I compiled with Maven and that worked fine too. I cherry-picked the patches, tho, as I don't like "merge" commits. Next time, please start a clean branch of the latest master. I also applied it to the 2.3 series, so should be part of BridgeDb 2.3.4 and that we can update the downstream tools using it.

**Comment by DeniseSl22** [comment]
> The patch looks fine. I compiled with Maven and that worked fine too. I cherry-picked the patches, tho, as I don't like "merge" commits. Next time, please start a clean branch of the latest master. I also applied it to the 2.3 series, so should be part of BridgeDb 2.3.4 and that we can update the downstream tools using it.

Okay, I'll do that next time.... @egonw : So you want me to make separate commits for each changed file, or for each changed database? And I used the QC_Updates because it (should have been) a complete branch.... But maybe I can remove that branch then now, and for next time make a new one? There shouldn't be anything pending in the old branch any more.

**Comment by egonw** [comment]
No, branch is fine. It's the merge patch in your branch that I'm not happy about. Btw, turns out your patch caused a lot of regressions.

**Pull request closed without merging**
