### PR TITLE
Bug Fix: QC tool should not throw an exception for older Derby files

### PR DESCRIPTION
**Pull request by The-Marvex**

### CODE REVIEW

**Comment by egonw** [comment]
I'll check this patch today. Initial though is that the version _should_ be available at a Java level.

**Comment by egonw** [comment]
@The-Marvex, can you check out if this works:

```java
Boolean isSchemaUpdated = "4".equals(newGdb.getInfo().get("schemaversion"));
```

Or something like that. If I look at the code, `newGdb.getInfo()` basically returns the content of the `info` table.

**Comment by The-Marvex** [comment]
on it.

**Comment by The-Marvex** [comment]
Actually, the newGdb and oldGdb both are SimpleGdb. getInfo is restricted to SimpleGdbImplCommon (it extends SimpleGdb) so we will not be able to use the method directly as you have proposed here. One way is to typecast SimpleGdb to SimpleGdbImplCommon and then use it to access the getInfo (for that we'll have to make the function scope public which currently is default i.e. not accessible outside the package)

**Comment by egonw** [comment]
Yes, sounds good. Did that approach work? I did not see a new commit yet.

**Comment by The-Marvex** [comment]
Wasn't working, was throwing this exception: "Exception in thread "main" java.lang.IllegalStateException: Must call cleanup() between two init() calls".

**Comment by egonw** [comment]
@The-Marvex, did you update this branch with changes? I am not sure if this PR is now ready for inclusion.

**Comment by The-Marvex** [comment]
This is complete. I didn't update because the above-mentioned idea didn't work. I tried different things along the same lines but none were working. The current PR is working

**Comment by egonw** [comment]
so, this one can just be closed? It is not longer relevant, and replaced by another PR?

**Comment by The-Marvex** [comment]
It is relevant, we don't any update to this PR, we can merge this.

**Pull request merged**
